apiVersion: apps/v1
kind: Deployment
metadata:
  name: nursery-backend
  labels:
    app: nursery-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nursery-backend
  template:
    metadata:
      labels:
        app: nursery-backend
    spec:
      containers:
      - name: nursery-backend
        image: kavitharc/bloom-haven-nursery:28
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_RUN_HOST
          value: "0.0.0.0"
        - name: FLASK_RUN_PORT  
          value: "5000"
