apiVersion: apps/v1
kind: Deployment
metadata:
  name: nursery-backend
  labels:
    app: nursery-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nursery-backend
  template:
    metadata:
      labels:
        app: nursery-backend
    spec:
      containers:
      - name: nursery-backend
        image: kavitharc/bloom-haven-nursery:28
        ports:
        - containerPort: 5000
        # Force Flask to bind to all interfaces
        command: ["python", "app.py", "--host=0.0.0.0", "--port=5000"]